version: '3.8'

services:
  savageapp:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "80:80"
      - "8080:8080"
      - "3000:3000"
    volumes:
      - ./sqlite:/app/sqlite
    restart: unless-stopped